// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN9zpc34kg7Dhwm27sXi9O4n33YBiRR6g',
    appId: '1:1076468959525:web:72f92ecd128f17cd7fb2cc',
    messagingSenderId: '1076468959525',
    projectId: 'ips-238dd',
    authDomain: 'ips-238dd.firebaseapp.com',
    storageBucket: 'ips-238dd.appspot.com',
    measurementId: 'G-S6N8KTK3NB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhKw8HFgfqP7T43yUlaTZTqCdye6LJudM',
    appId: '1:1076468959525:android:7eb6597a14ad383a7fb2cc',
    messagingSenderId: '1076468959525',
    projectId: 'ips-238dd',
    storageBucket: 'ips-238dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIt2fMdBzbPiZNLCbo3vVH0w35oXopC00',
    appId: '1:1076468959525:ios:e4093aa6905c66777fb2cc',
    messagingSenderId: '1076468959525',
    projectId: 'ips-238dd',
    storageBucket: 'ips-238dd.appspot.com',
    iosBundleId: 'com.example.joe',
  );
}
